### PR TITLE
Added url to ossindex-maven-plugin's pom.xml

### LINKED ISSUE #52: ossindex-maven-plugin has wrong url in pom file
## Problem

`ossindex-maven-plugin` does not define a project URL in the pom file. In that case, maven inherits the value of the parent pom and appends the artifact id (see [maven documentation](https://maven.apache.org/ref/3.6.1/maven-model-builder/)).
By that maven resolves the URL to https://sonatype.github.io/ossindex-maven/ossindex-maven-plugin/, which does not exist.

## Suggested Solution

Add an URL tag to `maven-plugin/pom.xml`

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #52

### CODE REVIEW

**Comment by redcatbear** [comment]
This fix would help getting the correct project URL when querying it via the Maven API.
Especially helpful when automatically generating dependency lists.

**Comment by jdillon** [comment]
+1

**Comment by jakobbraun** [comment]
Any chance to get this merged?

**Comment by DarthHater** [comment]
@jakobbraun for posterities sake, can you go sign our CLA and just let me know when you have? https://sonatypecla.herokuapp.com/sign-cla

It's a small change, but it'll be nice to have for any future contributions!

**Comment by jakobbraun** [comment]
sure, done

**Pull request merged**
